- name: extract artifact
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu

-- name: "Install NodeJS"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install NPM"
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes 

- name: start app
  become: yes
  command: |
    pm2 start npm -- start